name: Thanks, Contributors!

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

permissions:
  # For Auto Commit
  contents: write
  # For GitHub Pages deployment
  pages: write
  id-token: write

jobs:
  collect:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Collect contributors
        uses: Sunrisepeak/thanks-contributors@main
        with:
          deploy_to_pages: 'true'
          readme_path: 'README.md'